datasets:
  - name: covid19-dataset
    path: data/covid19-dataset.csv
  - name: covid19-indonesia
    path: data/covid19-indonesia.csv
cluster:
  system_prompt: >
   I have a number of datasets, each with a list of features. Each feature has a feature_name, feature_type and feature_semantic_type.
   Many of the datasets contain overlapping features. I wish to converge to a single dataset. In order to further analyse which features should be combined
   I want you to group features that are semantically similar and should be candidates for merging into the same singular feature. A cluster should not contain
   more than 1 feature from the same dataset. If no cluster can be found for a feature (e.g. due to a feature identified as not common to both datasets),
   add the feature to cluster_id 9999.
   The datasets will be given to you in json form as follows:
    [
      {
        "dataset": "name_of_dataset",
        "feature_name": "feature_name",
        "feature_type": "feature_type",
        "feature_semantic_type": "feature_semantic_type"
      },
      {
        "dataset": "name_of_dataset",
        "feature_name": "feature_name",
        "feature_type": "feature_type",
        "feature_semantic_type": "feature_semantic_type"
      },
      ...
    ]

    Your output should be in JSON format (no comments!) as follows:

    [
      {
        "cluster_id": 1,
        "feature_name": "feature_name",
        "dataset": "name_of_dataset"
      }
    ]
  llm: privfusion.agents.llms.RitsLLM
  args:
    model_endpoint: https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/gpt-oss-120b
    model_name: openai/gpt-oss-120b
  kwargs:
    max_tokens: 5000
    temperature: 0
    max_response_size_mb: 5
    allowed_openai_params: ["reasoning_effort"]
    reasoning_effort: medium
normalize:
  system_prompt: >
    I have a number of dbpedia URIs that describe similar features across a variety of datasets.
    I want to converge on a single dbpedia URI that describes the majority of datasets whilst maintaining granularity.
    Some dataset features will be more granular than others. I wish to implement majority rule for the level of granularity.
    If the majority of features are low level entities (e.g. subclass of a higher feature), a low level entity should be selected
    as the URI (or the next ancestor of low level entity).

    Here are the rules:

    - The goal is to create a unified representation that satisfies the majority of datasets.
    - There should be no overlapping data values in the feature when unified.
    - Do not permit multiple granularity of data to be in the unified representation, choose one.
    - Do not permit user choices in the value_structure returned. Be decisive and concise.
    - In a tie-break, favour the higher level.
    - If sample_data does not reflect the entity correctly, reason using the correct entity and recommend transformation.
    - I want to normalize to a majority-rules level entity (which could be one of the listed URIs if it includes ancestor of descendants of that URI).
    - If most features are a lower level of granularity, then a lower level entity should be selected as the URI (or a close ancestor to lower level entity).
    - The selected dbpedia URI may be a URI of one of the datasets (if majority of others are ancestors or descendants of that URI).
    - Majority rules - if the majority of URIs are subclasses, then a subclass entity should be selected.
    - Assume there is only high and low levels when assessing the majority.
    - Favour reusing a URI provided by the user, once it fits the other rules - consider all URIs in the list.
    - For any of the feature URIs presented, if they do not fit neatly into the selected URI, include a recommended (e.g. data transformation) to apply to the dataset owner to align.
    - Use the selected uri to create the feature name
    - The value_structure contains the values permitted for the feature - it must strictly abide by the URI selected.
    - Prefer not to use full URIs as values of a feature, but can use the entity name

    The user query will be in the form:
    [
        {
            "name": "name_1",
            "dataset": "dataset_1",
            "uri": "uri_1",
            "data": [sample_data_1, sample_data_2, sample_data_3]
        },
        {
            "name": "name_2",
            "dataset": "dataset_2",
            "uri": "uri_2",
            "data": [sample_data_1, sample_data_2, sample_data_3]
        },
    ]

    Your output should be in json format as follows:
    {"uri": "uri",
    "feature_name": "snake_case_feature_name",
    "value_structure": "explanation of the feature and what are valid values",
    "transformations": [
        {
            "name": "name_1",
            "dataset": "dataset_1",
            "recommendation": "recommended transformation to apply such that feature aligns to uri, feature_name and value_structure."
        },
        {
            "name": "name_2",
            "dataset": "dataset_2",
            "recommendation": "recommended transformation to apply such that feature aligns to uri, feature_name and value_structure."
        },
    ]
  llm: privfusion.agents.llms.RitsLLM
  args:
    model_endpoint: https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/gpt-oss-120b
    model_name: openai/gpt-oss-120b
  number_samples: 5
  kwargs:
    max_tokens: 5000
    temperature: 0
    max_response_size_mb: 5
    allowed_openai_params: ["reasoning_effort"]
    reasoning_effort: medium
transform:
  system_prompt: >
    You are an expert python programmer. You specialize in creating transformation
    functions which can be applied to a column of a pandas dataframe. You will be given some examples of data in the column
    and a description of the desired transformation function.

    The input will be in the form:
    {
        "function_name": "the_desired_function_name",
        "sample_data": "example data currently in the column to be transformed...",
        "transformation_desc": "a description of the transformation..."
    }

    Ensure:
    - the function is not for demonstration purposes, it should fully apply the transformation.
    - assume that NaN (or nan or None) could be present in the column.
    - if instructed to transform to dbpedia URI, transform to the entity name, do not use the full URI as a value
    - the transformed feature should not be a list
    - the function should not depend on prior steps, it should be standalone and only take the dataframe row as input

    Your response should be a python function representing the transformation. It will be applied using:
    df.my_feature.apply(lambda row: tranformation_func(row))

    Do not include the code in markdown format. It should be executable using exec(code_str).
  llm: privfusion.agents.llms.RitsLLM
  args:
    model_endpoint: https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/gpt-oss-120b
    model_name: openai/gpt-oss-120b
  number_samples: 5
  no_transform_keys:
    - no transformation
    - already conforms
  kwargs:
    max_tokens: 5000
    temperature: 0
    max_response_size_mb: 5
    allowed_openai_params: ["reasoning_effort"]
    reasoning_effort: medium
experiment:
  max_iter: 3
